### ISSUE TITLE
Going through the provided steps in the README.md doesn't result in expected change of flags

### ISSUE THREAD

**Issue by patrick-ve** [Modwake/customFlags#1]
I have gone through all steps provided in the README.md (labelled under the **AUTOMATIC** section of the tutorial), but when I launch the game the vanilla flags are still present when I construct my own ships. 

The instructions for copying and adding the provided .dll files are quite clear, but I do not understand what the following lines of code in steamID.txt do:

```
1stSTEAMID64=portFlag.png
MySTEAMID64=Pineapple.png
123456789123=AUS.png
```

Am I allowed to name these .png files into anything I'd like? What does 123456789123 refer to; is it my STEAMID64? Can I just place one single flag into the folder /Mods/Assets/FlagReplacement and add the filename to all entries in steamID.txt? This is what I came unsuccessfully came up with:

```
1stSTEAMID64=flag.png
MySTEAMID64=flag.png
76561197995260065=flag.png
```

Am I doing something wrong?

**Comment by cheesenibbles123** [comment]
The lines within the `steamID.txt` simply act as the link between the `STEAMID64` and the name of the flag to use. You can use any name of flag that you wish, as long as the flag name inside the `steamID.txt` file is the same. It auto generates a base template inside the txt for you to use, this is the template if I remember correctly:
```
STEAMID64HERE=FLAGNAMEHERE
```
Try inserting the flag name without the `.png` extension, im not sure but I believe that I removed the need for it, but forgot to update the guide. 

For example, use the following inside your **steamID.txt**:
```
76561197995260065=flag
```
And name your flag image `flag.png`

**Comment by cheesenibbles123** [comment]
Also, whilst ingame, if it still fails, you can press **insert** to bring up the modloader menu. If you go to the **logs** tab, anything prefixed with `[FlagReplacement]` is likely an error from the mod. So that might be able to help if the above doesn't work.

**Comment by cheesenibbles123** [comment]
@patrick-ve If/when you give it a test in the future let me know. I'm fairly certain it's to do with me updating the guide, as the image shown on the readme was taken using the same build that is provided but I could be wrong. I've modified the ReadMe to try and make it clearer, if any of it is still confusing let me know so I can try and improve it.

**Comment by cheesenibbles123** [comment]
Closed due to:
No response after 2 weeks.
